const dummyTokens = [
  {
    id: 1,
    name: "Ethereum",
    symbol: "ETH",
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    price: 3250,
    change: 2.45,
    raised: 250,
    goal: 500,
  },
  {
    id: 2,
    name: "Bitcoin",
    symbol: "BTC",
    logo: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    price: 61200,
    change: -1.12,
    raised: 180,
    goal: 300,
  },
  {
    id: 3,
    name: "Solana",
    symbol: "SOL",
    logo: "https://cryptologos.cc/logos/solana-sol-logo.png",
    price: 185,
    change: 3.25,
    raised: 35,
    goal: 200,
  },
  {
    id: 4,
    name: "Arbitrum",
    symbol: "ARB",
    logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
    price: 1.12,
    change: 1.98,
    raised: 120,
    goal: 250,
  },
  {
    id: 5,
    name: "Polygon",
    symbol: "MATIC",
    logo: "https://cryptologos.cc/logos/polygon-matic-logo.png",
    price: 0.89,
    change: -0.67,
    raised: 75,
    goal: 150,
  },
  {
    id: 6,
    name: "Chainlink",
    symbol: "LINK",
    logo: "https://cryptologos.cc/logos/chainlink-link-logo.png",
    price: 18.2,
    change: 4.8,
    raised: 300,
    goal: 500,
  },
  {
    id: 7,
    name: "Aptos",
    symbol: "APT",
    logo: "https://cryptologos.cc/logos/aptos-apt-logo.png",
    price: 7.65,
    change: 5.3,
    raised: 60,
    goal: 120,
  },
  {
    id: 8,
    name: "Optimism",
    symbol: "OP",
    logo: "https://cryptologos.cc/logos/optimism-ethereum-op-logo.png",
    price: 2.35,
    change: -2.1,
    raised: 140,
    goal: 250,
  },
  {
    id: 9,
    name: "Base",
    symbol: "BASE",
    logo: "https://cryptologos.cc/logos/base-base-logo.png",
    price: 0.65,
    change: 6.25,
    raised: 220,
    goal: 300,
  },
  {
    id: 10,
    name: "Uniswap",
    symbol: "UNI",
    logo: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
    price: 9.45,
    change: 2.9,
    raised: 130,
    goal: 250,
  },
];

export default dummyTokens;